#server config
server.port=8080
server.servlet.context-path=/
server.servlet.application-display-name=app
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=utf-8
#mvc config
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
#jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
#redis
spring.redis.client-type=jedis
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.cache-names=default
spring.cache.redis.time-to-live=1m
#log
logging.config=classpath:logback.xml
#api docs config
knife4j.enable=true
