-- ----------------------------
-- TABLE STRUCTURE FOR SYS_ORG
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ORG`;
CREATE TABLE `SYS_ORG`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ORG_ID` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NOT NULL,
  `ORG_CODE` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL,
  `ORG_NAME` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NOT NULL,
  `ORG_PARENT_ID` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL,
  `ORG_SHORT_NAME` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL,
  `ORG_TYPE` INT(1) NULL DEFAULT NULL,
  `ORG_STATUS` INT(1) NULL DEFAULT NULL,
  `ORG_LEVEL` INT(11) NULL DEFAULT NULL,
  `ORG_SEQ` VARCHAR(1000) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL,
  `CREATE_PK` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '创建人主键',
  `CREATE_BY` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '创建人名称',
  `CREATE_TIME` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `MODIFY_PK` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '修改人主键',
  `MODIFY_BY` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '修改人名称',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `ORGIDX`(`ORG_ID`) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 1 CHARACTER SET = UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- TABLE STRUCTURE FOR SYS_USER
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '逻辑主键',
  `USER_ID` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NOT NULL COMMENT '用户主键',
  `USER_CODE` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NOT NULL COMMENT '用户代码',
  `USER_PWD` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NOT NULL COMMENT '用户密码',
  `USER_NAME` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '用户姓名',
  `USER_NAME_ENC` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '加密用户姓名',
  `USER_SEX` INT(1) NULL DEFAULT 0 COMMENT '用户性别0女1男',
  `USER_TYPE` INT(1) NULL DEFAULT NULL COMMENT '用户类型',
  `USER_STATUS` INT(1) NOT NULL DEFAULT 0 COMMENT '用户状态 1正常 0禁用 2冻结',
  `USER_SORT` INT(11)  NULL DEFAULT NULL COMMENT '用户顺序',
  `USER_EMAIL` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '工作邮箱',
  `USER_EMAIL_ENC` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '加密后邮箱',
  `USER_TEL` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '办公电话',
  `USER_TEL_ENC` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '加密后电话',
  `USER_MOBILE` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '用户手机',
  `USER_MOBILE_ENC` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '加密后的手机',
  `CREATE_PK` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '创建人主键',
  `CREATE_BY` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '创建人名称',
  `CREATE_TIME` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `MODIFY_PK` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '修改人主键',
  `MODIFY_BY` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '修改人名称',
  `MODIFY_TIME` DATETIME NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDXUSERID`(`USER_ID`) USING BTREE,
  UNIQUE INDEX `IDEXUSERCODE`(`USER_CODE`) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 1 CHARACTER SET = UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- TABLE STRUCTURE FOR SYS_USER_ORG
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER_ORG`;
CREATE TABLE `SYS_USER_ORG`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NOT NULL COMMENT '用户主键',
  `ORG_ID` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NOT NULL COMMENT '机构主键',
  `ORG_STATUS` INT(1) NOT NULL COMMENT '当前记录状态',
  `ORG_DEFAULT` INT(1) NULL DEFAULT NULL COMMENT '是否是默认部门',
  `ORG_SORT` INT(11) NULL DEFAULT NULL COMMENT '排序',
  `ORG_SEQ` VARCHAR(1000) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '所在部门完整主键拼接路径',
  `ORG_SEQ_CN` VARCHAR(2000) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '所在部门汉字拼接路径',
  `CREATE_PK` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NOT NULL COMMENT '创建人主键',
  `CREATE_BY` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NOT NULL COMMENT '创建人名称',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `MODIFY_PK` VARCHAR(32) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '修改人主键',
  `MODIFY_BY` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI NULL DEFAULT NULL COMMENT '修改人名称',
  `MODIFY_TIME` DATETIME NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `ORGIDX`(`ORG_ID`) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 1 CHARACTER SET = UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI ROW_FORMAT = DYNAMIC;

